# Generated by Django 4.2.2 on 2023-09-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0002_investimento_niel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimento',
            old_name='niel',
            new_name='nivel',
        ),
    ]
