# Generated by Django 4.2.2 on 2023-09-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0003_rename_niel_investimento_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='nivel',
        ),
    ]
